### ISSUE TITLE
How to address multiple trigers?

### ISSUE THREAD

**Issue by NoroNetwork** [pengowray/ScreenSleeper#1]
Hello, 

i am triing to get to screan to turn on and off on sensor state. 

But i cant get mqttConfig.json configured for multiple trigers. 

Can you please point me? 
I read documentation but i cant get it to work. 

Thnaks.

**Comment by pengowray** [comment]
Hello, nice to see the project is being used by others.

Here's an example of what the config should look like with multiple triggers. (I have not tested it)

```json
  "Triggers": [
    {
      "Action": "Lock",
      "Topic": "indoor_habitat/lock/set",
      "Payload": "on"
    },
    {
      "Action": "ScreenOff",
      "Topic": "indoor_habitat/screenoff/set",
      "Payload": "on"
    },
    {
      "Action": "ScreenOn",
      "Topic": "indoor_habitat/screenon/set",
      "Payload": "on"
    }
  ]
```

 Let me know if it works (or something like it). If it's all good I'll add it to the docs.

**Comment by kubert96** [comment]
Hello, 

thnaks for the quick response :) 

**It is working.** 

Thank you. 
Keep up the good work. 


`  "Triggers": [
    {
      "Topic": "my_pc/sleep/set",
      "Payload": "off"
      "Action": "ScreenOff",
    },
    {
      "Topic": "my_pc/sleep/set",
      "Payload": "on"
      "Action": "ScreenOn",
    }
  ]`

**Comment by NoroNetwork** [comment]
Hello, 

thnaks for the quick response :) 

**It is working.** 

Thank you. 
Keep up the good work. 

```
  "Triggers": [
    {
      "Topic": "my_pc/sleep/set",
      "Payload": "off"
      "Action": "ScreenOff",
    },
    {
      "Topic": "my_pc/sleep/set",
      "Payload": "on"
      "Action": "ScreenOn",
    }
  ]
```
